# Generated by Django 5.0.10 on 2025-01-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSearchRecord",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                ("interview_status", models.IntegerField(blank=True, null=True)),
                ("application_result", models.IntegerField(blank=True, null=True)),
                ("job_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_search_record",
                "managed": False,
            },
        ),
    ]
